---
- name: Set services
  set_fact:
    compose_services:
      version: "3.9"
      networks:
        net_01:
      services:
        postgres:
          image: agostops/agoston-postgres:v14.4.0
          command: >
            -c search_path='agoston_public,agoston_api,agoston_identity,agoston_metadata,public'
            -c shared_preload_libraries='pg_cron'
            -c cron.database_name='agoston'
            -c timezone='{{ time_zone }}'
            -c tcp_keepalives_idle=60
          environment:
            - POSTGRES_DB=agoston
            - POSTGRES_PASSWORD={{ stack_services.postgres.postgres_password }}
            - PGDATA=/var/lib/postgresql/data/pgdata
          volumes:
            - "{{ persistent_pgdata_path }}:/var/lib/postgresql/data"
          deploy:
            placement:
              constraints:
                - node.labels.{{ backend_uuid }}_postgres_node_type==rw
            restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
            resources:
              limits:
                cpus: "{{ stack_services.postgres.resources.limits.cpus }}"
                memory: "{{ stack_services.postgres.resources.limits.memory }}"
              reservations:
                cpus: "{{ stack_services.postgres.resources.reservations.cpus }}"
                memory: "{{ stack_services.postgres.resources.reservations.memory }}"
          sysctls:
            - net.ipv4.tcp_keepalive_time=60
          networks:
            - net_01
          ports:
            - "{{ stack_services.postgres.http_port_listening }}:5432"

        pgadmin:
          depends_on:
            - postgres
          image: dpage/pgadmin4:6.12
          environment:
            - PGADMIN_DEFAULT_EMAIL={{ backend_uuid }}@agoston.io
            - PGADMIN_DEFAULT_PASSWORD={{ stack_services.postgres.developer_password }}
            - PGADMIN_CONFIG_APP_COPYRIGHT=''
            - PGADMIN_CONFIG_APP_NAME='Postgres Console for Agoston'
            - PGADMIN_CONFIG_APP_ICON=''
            - PGADMIN_CONFIG_AUTO_DISCOVER_SERVERS=False
            - PGADMIN_CONFIG_SHOW_GRAVATAR_IMAGE=False
            - PGADMIN_CONFIG_MFA_ENABLED=False
          volumes:
            - "{{ persistent_pgadmin_path }}/pgadmin/data:/var/lib/pgadmin"
            - "{{ persistent_pgadmin_path }}/pgadmin/servers.json:/pgadmin4/servers.json"
          deploy:
            restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
            resources:
              limits:
                cpus: "{{ stack_services.pgadmin.resources.limits.cpus }}"
                memory: "{{ stack_services.pgadmin.resources.limits.memory }}"
              reservations:
                cpus: "{{ stack_services.pgadmin.resources.reservations.cpus }}"
                memory: "{{ stack_services.pgadmin.resources.reservations.memory }}"
          sysctls:
            - net.ipv4.tcp_keepalive_time=60
          networks:
            - net_01
          ports:
            - "{{ stack_services.pgadmin.http_port_listening }}:80"

        graphile:
          depends_on:
            - postgres
          image: agostops/agoston-graphile:v1.2.5
          environment:
            - ENVIRONMENT_NAME={{ stack_services.graphile.environment }}
            - HTTP_PORT_LISTENING=4000
            - HTTP_BACKEND_ORIGIN={{ stack_services.graphile.http.backend_origin }}
            - PGHOST=postgres
            - PGDATABASE=agoston
            - POSTGRES_PASSWORD={{ stack_services.postgres.postgres_password }}
            - POSTGRAPHILE_PASSWORD={{ stack_services.postgres.graphile_password }}
            - DEVELOPER_PASSWORD={{ stack_services.postgres.developer_password }}
            - POSTGRAPHILE_DB_SCHEMA=agoston_public
            - POSTGRAPHILE_DEFAULT_ROLE=anonymous
            - CORS_ORIGIN={{ stack_services.graphile.cors_origin }}
            - RECAPTCHA_SCORE_THRESHOLD={{ stack_services.graphile.recaptcha.score_threshold }}
            - RECAPTCHA_SECRET_KEY={{ stack_services.graphile.recaptcha.secret_key }}
            - SESSION_COOKIE_SECRET={{ stack_services.graphile.session_cookie_secret }}
            - AUTH_REDIRECT_WHEN_SUCCESS={{ stack_services.graphile.auth.redirect_when_success }}
            - AUTH_REDIRECT_WHEN_ERROR={{ stack_services.graphile.auth.redirect_when_error }}
            - AUTH_REDIRECT_LOGOUT={{ stack_services.graphile.auth.redirect_logout }}
            - AUTH_STRATEGIES={{ stack_services.graphile.auth.strategies|to_json(ensure_ascii=False)|string }}
            - NODE_ENV=production
          deploy:
            restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
            resources:
              limits:
                cpus: "{{ stack_services.graphile.resources.limits.cpus }}"
                memory: "{{ stack_services.graphile.resources.limits.memory }}"
              reservations:
                cpus: "{{ stack_services.graphile.resources.reservations.cpus }}"
                memory: "{{ stack_services.graphile.resources.reservations.memory }}"
          sysctls:
            - net.ipv4.tcp_keepalive_time=60
          networks:
            - net_01
          ports:
            - "{{ stack_services.graphile.http_port_listening }}:4000"

        worker:
          depends_on:
            - postgres
          image: agostops/agoston-worker:v1.2.0
          environment:
            - ENVIRONMENT_NAME={{ stack_services.worker.environment }}
            - POSTGRAPHILE_DB_URI=postgres://postgraphile:{{ stack_services.postgres.graphile_password }}@postgres:5432/agoston?sslmode=disable
            - WORKER_CONCURRENCY={{ stack_services.worker.concurrency }}
            - WORKER_POLL_INTERVAL={{ stack_services.worker.poll_interval }}
            - NODE_ENV=production
          deploy:
            restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
            resources:
              limits:
                cpus: "{{ stack_services.worker.resources.limits.cpus }}"
                memory: "{{ stack_services.worker.resources.limits.memory }}"
              reservations:
                cpus: "{{ stack_services.worker.resources.reservations.cpus }}"
                memory: "{{ stack_services.worker.resources.reservations.memory }}"
          sysctls:
            - net.ipv4.tcp_keepalive_time=60
          networks:
            - net_01
