---
- name: Create/restart services stack
  run_once: yes
  become: yes
  community.docker.docker_compose:
    project_name: "agoston-backend"
    state: present
    restarted: true
    definition: "{{ compose_services }}"
