---
- name: Pull backend images
  become: yes
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - "{{ compose_services.services.postgres.image }}"
    - "{{ compose_services.services.graphile.image }}"
