---
- name: Create host pgdata persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ persistent_pgdata_path }}"
    state: directory
    owner: "{{ stack_services.postgres.user_id }}"
    group: "{{ stack_services.postgres.group_id }}"
    mode: '0750'
