---
- name: Create host pgdata persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ persistent_pgdata_path }}"
    state: directory
    owner: '999'
    group: '999'
    mode: '0750'

- name: Create host pgadmin persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ persistent_pgadmin_path }}"
    state: directory
    owner: '5050'
    group: '5050'
    mode: '0750'
    state: directory
