---
- name: Create host pgdata persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ persistent_pgdata_path }}"
    state: directory
    owner: "{{ postgres_user_id }}"
    group: "{{ postgres_group_id }}"
    mode: '0750'
