---
- name: Create host pgadmin persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: '5050'
    group: '5050'
    mode: '0750'
  loop:
    - "{{ persistent_pgadmin_path }}"
    - "{{ persistent_pgadmin_path }}/pgadmin"
    - "{{ persistent_pgadmin_path }}/pgadmin/data"

- name: Create host pgadmin persistent directory
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: '5050'
    group: '5050'
    mode: '0750'
  loop:
    - "{{ persistent_pgadmin_path }}"
    - "{{ persistent_pgadmin_path }}/pgadmin"
    - "{{ persistent_pgadmin_path }}/pgadmin/data"
    - "{{ persistent_pgadmin_path }}/pgadmin/data/storage"

- name: Copy pgadmin configuration servers.json
  become: yes
  ansible.builtin.copy:
    dest: "{{ persistent_pgadmin_path }}/pgadmin/servers.json"
    owner: '5050'
    group: '5050'
    mode: '0600'
    content: |
      {
          "Servers": {
              "agoston": {
                  "Name": "agoston",
                  "Group": "Servers",
                  "Host": "postgres",
                  "Port": 5432,
                  "Username": "developer",
                  "SSLMode": "prefer",
                  "DBRestriction": "agoston",
                  "MaintenanceDB": "agoston",
                  "Comment": "Server pre-configured for your backend"
              }
          }
      }